Updated py-borgbackup to 1.0.8.
Version 1.0.8 (2016-10-29)

Bug fixes:

    RemoteRepository: Fix busy wait in call_many, #940

New features:

    implement borgmajor/borgminor/borgpatch placeholders, #1694 {borgversion} was already there (full version string). With the new placeholders you can now also get e.g. 1 or 1.0 or 1.0.8.

Other changes:

    avoid previous_location mismatch, #1741

    due to the changed canonicalization for relative pathes in PR #1711 / #1655 (implement /./ relpath hack), there would be a changed repo location warning and the user would be asked if this is ok. this would break automation and require manual intervention, which is unwanted.

    thus, we automatically fix the previous_location config entry, if it only changed in the expected way, but still means the same location.

    docs:
        deployment.rst: do not use bare variables in ansible snippet
        add clarification about append-only mode, #1689
        setup.py: add comment about requiring llfuse, #1726
        update usage.rst / api.rst
        repo url / archive location docs + typo fix
        quickstart: add a comment about other (remote) filesystems

    vagrant / tests:
        no chown when rsyncing (fixes boxes w/o vagrant group)
        fix fuse permission issues on linux/freebsd, #1544
        skip fuse test for borg binary + fakeroot
        ignore security.selinux xattrs, fixes tests on centos, #1735

Version 1.0.8rc1 (2016-10-17)

Bug fixes:

    fix signal handling (SIGINT, SIGTERM, SIGHUP), #1620 #1593 Fixes e.g. leftover lock files for quickly repeated signals (e.g. Ctrl-C Ctrl-C) or lost connections or systemd sending SIGHUP.
    progress display: adapt formatting to narrow screens, do not crash, #1628
    borg create --read-special - fix crash on broken symlink, #1584. also correctly processes broken symlinks. before this regressed to a crash (5b45385) a broken symlink would've been skipped.
    process_symlink: fix missing backup_io() Fixes a chmod/chown/chgrp/unlink/rename/... crash race between getting dirents and dispatching to process_symlink.
    yes(): abort on wrong answers, saying so, #1622
    fixed exception borg serve raised when connection was closed before reposiory was openend. add an error message for this.
    fix read-from-closed-FD issue, #1551 (this seems not to get triggered in 1.0.x, but was discovered in master)
    hashindex: fix iterators (always raise StopIteration when exhausted) (this seems not to get triggered in 1.0.x, but was discovered in master)
    enable relative pathes in ssh:// repo URLs, via /./relpath hack, #1655
    allow repo pathes with colons, #1705
    update changed repo location immediately after acceptance, #1524
    fix debug get-obj / delete-obj crash if object not found and remote repo, #1684
    pyinstaller: use a spec file to build borg.exe binary, exclude osxfuse dylib on Mac OS X (avoids mismatch lib <-> driver), #1619

New features:

    add "borg key export" / "borg key import" commands, #1555, so users are able to backup / restore their encryption keys more easily.

    Supported formats are the keyfile format used by borg internally and a special "paper" format with by line checksums for printed backups. For the paper format, the import is an interactive process which checks each line as soon as it is input.

    add "borg debug-refcount-obj" to determine a repo objects' referrer counts, #1352

Other changes:

    add "borg debug ..." subcommands (borg debug-* still works, but will be removed in borg 1.1)
    setup.py: Add subcommand support to build_usage.
    remote: change exception message for unexpected RPC data format to indicate dataflow direction.
    improved messages / error reporting:
        IntegrityError: add placeholder for message, so that the message we give appears not only in the traceback, but also in the (short) error message, #1572
        borg.key: include chunk id in exception msgs, #1571
        better messages for cache newer than repo, #1700
    vagrant (testing/build VMs):
        upgrade OSXfuse / FUSE for macOS to 3.5.2
        update Debian Wheezy boxes, #1686
        openbsd / netbsd: use own boxes, fixes misc rsync installation and fuse/llfuse related testing issues, #1695 #1696 #1670 #1671 #1728
    docs:
        add docs for "key export" and "key import" commands, #1641
        fix inconsistency in FAQ (pv-wrapper).
        fix second block in "Easy to use" section not showing on GitHub, #1576
        add bestpractices badge
        link reference docs and faq about BORG_FILES_CACHE_TTL, #1561
        improve borg info --help, explain size infos, #1532
        add release signing key / security contact to README, #1560
        add contribution guidelines for developers
        development.rst: add sphinx_rtd_theme to the sphinx install command
        adjust border color in borg.css
        add debug-info usage help file
        internals.rst: fix typos
        setup.py: fix build_usage to always process all commands
        added docs explaining multiple --restrict-to-path flags, #1602
        add more specific warning about write-access debug commands, #1587
        clarify FAQ regarding backup of virtual machines, #1672
    tests:
        work around fuse xattr test issue with recent fakeroot
        simplify repo/hashindex tests
        travis: test fuse-enabled borg, use trusty to have a recent FUSE
        re-enable fuse tests for RemoteArchiver (no deadlocks any more)
        clean env for pytest based tests, #1714
        fuse_mount contextmanager: accept any options