Update to 1.509.3
Changelog:
What's new in 1.509.3 (2013/09/09)

    Standalone install does not work with Apache + mod_proxy_ajp + SSL (issue 5753)
    Reload configuration from disk no longer works after upgrade to Jenkins 1.512. (issue 17977)
    Build Now link on MultiJob page doesn't work (issue 16974)
    Add descriptions for custom tools (issue 18771)
    Lazy loading causes massive delays after a period of inactivity when loading dashboard (issue 16023)
    NPE running matrix job (issue 18024)
    LastSuccessful and LastStable symlinks are invalid under Windows (issue 17681)
    IllegalStateException from MavenProject.getParent can break MavenFingerprinter.recordParents (issue 17775)
    NPE (isEmpty) from main.groovy (issue 15309)
    DependencyClassLoader#getTransitiveDependencies returns disabled plugins (issue 18654)
    parameter description don't use MarkupFormatter (issue 18427)
    Incompatible signature change in 1.489: AbstractProject.doBuild (issue 18356)
    Display Name is not shown (issue 17715)
    Fingerprint throws exceptions on 1.518 (issue 18337)
    FingerprintAction deserialization leads to NPE (issue 17125)
    update view via REST API doesn't work (issue 17302)
    MavenModuleSetBuild.getResult is expensive (issue 18895)
    Builds disappear from jobs - hudson.util.IOException2: Invalid directory name - java.text.ParseException: Unparseable date: "39" (issue 15587)
    Outdated JRuby libs (issue 14351)
    Fingerprint performance (issue 16301)
    10,000+ jobs tied to a label make Node index page unusably unresponsive (issue 18660)
    "Delete Project" link fails with 403 Exception: No valid crumb was included in the request (issue 18032)
    Manually uploaded plugins are incorrectly unpacked (issue 4543)
    Decorated Launcher Does Not Maintain "isUnix" for RemoteLauncher (issue 18368)
    Test harness packs copies of Maven into plugin archive (issue 18918)
    All Maven 2 builds fail with java.lang.NoSuchMethodError DigestUtils.md5Hex (issue 18178)