Update to 1.0.4:
    proxymngr 1.0.4

    Stop checking if pointers are NULL before passing them to free()

    Stop casting results of malloc calls

    Replace last strcpy call + manual append with snprintf call

    Replace malloc(strlen)+strcpy sets with strdup calls

    Ensure memory is initialized before use in PushRequestorQueue
    If authLen <= 0, then we weren't initializing the authName & authData
    pointers until after checking if all the allocations succeeded, but
    if any allocations failed, we'd then try to free them before that.

    Error: Uninitialised memory (CWE 456)
       Possible access to uninitialised memory '&newreq->authData'
            at line 590 of pmdb.c in function 'PushRequestorQueue'.
              &newreq->authData allocated at line 559.
              &newreq->authData uninitialised when authLen <= 0 at line 568.
            at line 591 of pmdb.c in function 'PushRequestorQueue'.
              &newreq->authData allocated at line 559.
              &newreq->authData uninitialised when authLen <= 0 at line 568
                  and newreq->authName == NULL at line 574.
       Possible access to uninitialised memory '&newreq->authName'
            at line 588 of pmdb.c in function 'PushRequestorQueue'.
              &newreq->authName allocated at line 559.
              &newreq->authName uninitialised when authLen <= 0 at line 568.
            at line 589 of pmdb.c in function 'PushRequestorQueue'.
              &newreq->authName allocated at line 559.
              &newreq->authName uninitialised when authLen <= 0 at line 568
                  and newreq->authName != NULL at line 574.

    [ This bug was found by the Parfait 1.5.1 bug checking tool.
      http://labs.oracle.com/pls/apex/f?p=labs:49:::::P49_PROJECT_ID:13 ]

    autogen.sh: Honor NOCONFIGURE=1
    See http://people.gnome.org/~walters/docs/build-api.txt

    configure: Drop AM_MAINTAINER_MODE

    This is not a GNU project, so declare it foreign.

    Assume signal handlers return void, as C89 requires
    Drops use of Imake's obsolete SIGNALRETURNSINT.