Update to 1.480.3
* Fix https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2013-02-16

Changelog:
What's new in 1.480.3 (2013/02/15)

    "Remember me on this computer" does not work, cookie is not accepted in new session (issue 16278)
    Slow/hung web UI in 1.483+ (stuck in parseURI) (issue 16474)
    Failure to delete old config files during rekeying on Windows (issue 16319)
    NoClassDefFoundError on Base64 when launching an headless slave with -jnlpCredential option (issue 9679)
    Loading asynchPeople calls (synch) People constructor (issue 16397)
    Jenkins briefly displays build queue and then it disappears until the page is reloaded (issue 15335)
    View.hasPeople too slow to use in sidepanel.jelly (issue 16244)
    XSS (SECURITY-46)
    File parameter causing data lost after Jenkins restart (issue 13536)