Remove libgnomeprint dependency, the package itself doesn't depend on it any longer.
Fixes build problem in evolution:
> ===> Creating toolchain wrappers for evolution-2.22.1
> ERROR: libgnomeprintui is not installed; can't buildlink files.

Bump BUILDLINK_ABI_DEPENDS.gtkhtml314 for dependency change.