Update to 1.4.4. Approved by wiz@. Tested on current with modular xorg.
Changes.
  commit a7970f5c817b5c75d945389cfaf1384ff23437f3
  Author: Matthieu Herrb <matthieu.herrb@laas.fr>
  Date:   Mon Aug 8 18:08:05 2011 +0200

    libXfont 1.4.4

    Signed-off-by: Matthieu Herrb <matthieu.herrb@laas.fr>
    Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>

  commit d11ee5886e9d9ec610051a206b135a4cdc1e09a0
  Author: Thomas Hoger <thoger@redhat.com>
  Date:   Mon Aug 8 18:03:09 2011 +0200

    LZW decompress: fix for CVE-2011-2895

    Specially crafted LZW stream can crash an application using libXfont
    that is used to open untrusted font files.  With X server, this may
    allow privilege escalation when exploited

    Reviewed-by: Matthieu Herrb <matthieu.herrb@laas.fr>
    Signed-off-by: Matthieu Herrb <matthieu.herrb@laas.fr>
    Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>

  commit 214ca6a7a2247544627e6dc7c8705811305ad007
  Author: Alan Coopersmith <alan.coopersmith@oracle.com>
  Date:   Mon May 16 18:28:13 2011 -0700

    Fix memory leak in allocation failure path of BitmapOpenScalable()

    Go ahead and fill in the font->info pointers so that
    bitmapUnloadScalable()
    will free the bits that were allocated, even if some were not.

    Error: Memory leak (CWE 401)
       Memory leak of pointer <unknown> allocated with
    ComputeScaledProperties(...)
            at line 1629 of
    /export/alanc/X.Org/git/lib/libXfont/src/bitmap/bitscale.c in function
    'BitmapOpenScalable'.
              pointer allocated at line 1616 with
    ComputeScaledProperties(...).
              <unknown> leaks when props != 0 at line 1623.

    [ This bug was found by the Parfait 0.3.7 bug checking tool.
      For more information see http://labs.oracle.com/projects/parfait/ ]

    Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
    Reviewed-by: Jeremy Huddleston <jeremyhu@apple.com>

  commit 7f8345aa6fb60a7fd7adf0095a2354fad1d8d5ef
  Author: Gaetan Nadon <memsize@videotron.ca>
  Date:   Wed Mar 2 14:33:07 2011 -0500

    doc: use common makefile for developers documentation

    The user/specs docs now have external references support.
    Developers doc are not installed so they do not participate.
    However, using a similar makefile shared amongst developers
    document reduces maintenance and is forward looking.

    Signed-off-by: Gaetan Nadon <memsize@videotron.ca>

  commit 77027deabca37183cfbbed107cf14ca80f29f26d
  Author: Gaetan Nadon <memsize@videotron.ca>
  Date:   Wed Feb 2 11:43:42 2011 -0500

    config: comment, minor upgrade, quote and layout configure.ac

    Group statements per section as per Autoconf standard layout
    Quote statements where appropriate.
    Autoconf recommends not using dnl instead of # for comments

    Use AC_CONFIG_FILES to replace the deprecated AC_OUTPUT with parameters.
    Add AC_CONFIG_SRCDIR([Makefile.am])

    This helps automated maintenance and release activities.
    Details can be found in http://wiki.x.org/wiki/NewModuleGuidelines

  commit 9ea1790d61bd135714c40e5089ecb1effa1dbcc0
  Author: Gaetan Nadon <memsize@videotron.ca>
  Date:   Thu Jan 27 18:50:15 2011 -0500

    config: remove AC_PROG_CC as it overrides AC_PROG_C_C99

    XORG_STRICT_OPTION from XORG_DEFAULT_OPTIONS calls
    AC_PROG_C_C99. This sets gcc with -std=gnu99.
    If AC_PROG_CC macro is called afterwards, it resets CC to gcc.

    Signed-off-by: Gaetan Nadon <memsize@videotron.ca>

  commit 4e0c6c45d819befdd9315d6282b957f7cfec3ae2
  Author: Paulo Zanoni <pzanoni@mandriva.com>
  Date:   Thu Dec 16 14:09:12 2010 -0200

    Use docbookx.dtd version 4.3 for all docs

    Signed-off-by: Paulo Zanoni <pzanoni@mandriva.com>
    Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>

  commit 01c30845853f5a8114467185d76274ae9bbff091
  Author: Alan Coopersmith <alan.coopersmith@oracle.com>
  Date:   Sun Nov 21 11:35:20 2010 -0800

    Sun's copyrights belong to Oracle now

    Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>

  commit 72ade58381a49514f2b29065ba33a464b7efc3d0
  Author: Gaetan Nadon <memsize@videotron.ca>
  Date:   Tue Nov 9 13:04:51 2010 -0500

    config: HTML file generation: use the installed copy of xorg.css

    Currenlty the xorg.css file is copied in each location
    where a DocBook/XML file resides. This produces about
    70 copies in the $(docdir) install tree.

    Signed-off-by: Gaetan Nadon <memsize@videotron.ca>

  commit 12157fbebc35c2d039df2df4fc5ac2b299eeec03
  Author: Alan Coopersmith <alan.coopersmith@oracle.com>
  Date:   Thu Oct 28 20:43:27 2010 -0700

    libXfont 1.4.3

    Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>

  commit f29f1d68d7eca96e45ba3758686be07993d82e03
  Author: Jesse Adkins <jesserayadkins@gmail.com>
  Date:   Tue Sep 28 13:30:02 2010 -0700

    Purge cvs tags.

    Signed-off-by: Jesse Adkins <jesserayadkins@gmail.com>
    Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>

  commit 6628b4d82426cf9ac240da363cd8a8252e6f71ef
  Author: Jeremy Huddleston <jeremyhu@apple.com>
  Date:   Mon Sep 27 12:31:50 2010 -0700

    FreeType: Cleanup MUMBLE and fix printing of XLFD in debug spew.

    Signed-off-by: Jeremy Huddleston <jeremyhu@apple.com>

  commit c482a2c104aa5cd1a265c2ca310a308dcc418fe7
  Author: Yaakov Selkowitz <yselkowitz@users.sourceforge.net>
  Date:   Wed Apr 14 05:58:28 2010 -0500

    Revert "Bug #6247: Fix build on Cygwin"

    libtool requires the '-no-undefined' flag in order to create shared
    libraries on PE/COFF platforms (Cygwin/MinGW); on other platforms this
    flag has no effect.

    The problem with libXfont is that PE weak symbols do not behave exactly
    as they do on ELF platforms.  Since PE binaries (both executables and
    libraries) must have all symbols resolved at link time, there is no way
    for the real symbols in xserver to "displace" those in libXfont at
    runtime, so the result is that libXfont uses its stubs, which do
    nothing, and xserver ends up unable to find its fonts.

    Solving this will require either significant changes to libXfont or some
    major improvement to the toolchain to handle this case.  Until that
    happens, removing '-no-undefined' will result in a static-only library
    on these platforms, which is the only currently working solution.

    http://sourceware.org/bugzilla/show_bug.cgi?id=11306
    http://cygwin.com/ml/cygwin/2010-04/msg00281.html

    This reverts commit 69c4ae1e3e14a58bc2eb9b9b8820dc7183b82a67.

    Conflicts:

        ChangeLog

    Signed-off-by: Yaakov Selkowitz <yselkowitz@users.sourceforge.net>

  commit 455ec66e82e3c4bedd9e789d2ab33030b8e64ffa
  Author: Alan Coopersmith <alan.coopersmith@oracle.com>
  Date:   Sun Aug 8 00:19:36 2010 -0700

    Fix builds with Sun compilers

    Sun compilers use #pragma weak in the *.c files to declare weak symbols,
    so should have weak defined to empty, but not define NO_WEAK_SYMBOLS

    Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>

  commit 0386fa77367a305deea3cc27f8a3865cc3c467c0
  Author: Jeremy Huddleston <jeremyhu@apple.com>
  Date:   Sat Jul 10 10:08:21 2010 -0700

    darwin: Fix build regression introduced by previous patch

    Signed-off-by: Jeremy Huddleston <jeremyhu@apple.com>

  commit 8f75706901da0141590d46f0f898e5678feac953
  Author: Jon TURNEY <jon.turney@dronecode.org.uk>
  Date:   Mon Jun 28 17:56:07 2010 +0100

    Build fix for platforms which don't have weak linkage

    Since we fix this by removing the serverGeneration symbol, assuming
    an external definition will be provided, this means on Windows libXfont
    can only be built as a static library (since PE shared libraries cannot
    contain undefined symbols).  This produces a libXfont which might only
    be useful to the xserver, but the only other users we might care about
    are xfs, which is obsolete, and bdftopcf, which fortunately doesn't
    pull in any objects which reference serverGeneration from libXfont.

    Signed-off-by: Jon TURNEY <jon.turney@dronecode.org.uk>
    Reviewed-by: Colin Harrison <colin.harrison@virgin.net>

  commit 5c49c956e9c85d89f6b2e719eb9b6fbde62c2f72
  Author: Gaetan Nadon <memsize@videotron.ca>
  Date:   Mon Jun 28 13:18:22 2010 -0400

    doc: use xorg-docs xorg.css stylesheet

    Use latest DocBook XML util-macros infrastructure

    Signed-off-by: Gaetan Nadon <memsize@videotron.ca>