Update sun-j*13 to version 1.0.15.
Changes according to http://java.sun.com/j2se/1.3/ReleaseNotes.html

Incorrect clsid is registered in windows registry for jre 1.3.1_14 release

NullPointerException with no stack trace
Focus disappears after deiconifying frame
Runtime exec hangs if ulimit nofiles is unlimite
CTW assertion at srcsharevmoptolock.cpp, 379
A bug of javax.swing.JTextField
GregorianCalendar uses wrong ERA value in non-lenient mode
Application crashes using :XX+UseTLE and -server on Windows
REGRESSION: 4789981 fails for 1.3.1_13-b01 on Solaris for Mozilla 1.0.1
java.lang.IllegalArgumentException: Signal already used by VM: SIGHUP
JCK: QuickSilver api test fails with -Xprof flag