Import ruby-activesupport-4.2.8 as devel/ruby-activesupport42
Notable changes since 3.2:
- Replace deprecated memcache-client gem with dalli in
  ActiveSupport::Cache::MemCacheStore.
- Optimize ActiveSupport::Cache::Entry to reduce memory and processing
  overhead.
- Inflections can now be defined per locale. singularize and pluralize
  accept locale as an extra argument.
- Object#try will now return nil instead of raise a NoMethodError if
  the receiving object does not implement the method, but you can still
  get the old behavior by using the new Object#try!.
- String#to_date now raises ArgumentError: invalid date instead of
  NoMethodError: undefined method 'div' for nil:NilClass when given an
  invalid date. It is now the same as Date.parse, and it accepts more
  invalid dates than 3.x.

See the release notes of 4.0, 4.1, and 4.2 for the full list:
- http://edgeguides.rubyonrails.org/4_0_release_notes.html
- http://edgeguides.rubyonrails.org/4_1_release_notes.html
- http://edgeguides.rubyonrails.org/4_2_release_notes.html