Update to 1.447.1
Changelog:
What's new in 1.447.1 (2012/03/28)

    File handle leak in serving static files (issue 13097)
    LDAP config error (issue 8152)
    jenkins running in Tomcat doesn't initalize slf4j properly (issue 12650)
    java.lang.NoClassDefFoundError: org.slf4j.impl.StaticLoggerBinder (issue 12446)
    Remote call on CLI channel from [ip] failed (issue 12302)
    jenkins does not start in jboss container (issue 12334)