Update to 1.0.5:
    xcmsdb 1.0.5

    _XcmsGetProperty: don't deal with uninitialized values, fail instead
    Import commit 502d414118c97d35a44f8e295709682022876331 from the
    master copy of this code in libX11.

    Only use results from GetWindowProperty if it returned Success
    Since Xlib prior to 1.6 didn't always clear values on failure, don't
    assume they're safe to use unless we succeeded.

    Reported by Oracle Parfait 1.5.1:
    Error: Uninitialised memory
       Uninitialised memory variable (CWE 457): Possible access to uninitialised memory variable 'ret_format'
            at line 743 of app/xcmsdb/xcmsdb.c in function 'RemoveSCCData'.
              ret_format allocated at line 733.
            at line 757 of app/xcmsdb/xcmsdb.c in function 'RemoveSCCData'.
              ret_format allocated at line 733.
       Uninitialised memory variable (CWE 457): Possible access to uninitialised memory variable 'ret_prop'
            at line 748 of app/xcmsdb/xcmsdb.c in function 'RemoveSCCData'.
              ret_prop allocated at line 731.
            at line 762 of app/xcmsdb/xcmsdb.c in function 'RemoveSCCData'.
              ret_prop allocated at line 731.

    Strip trailing whitespace from source files
    git ls-files | xargs gsed -i 's/[ \t]*$//'

    autogen.sh: Honor NOCONFIGURE=1
    See http://people.gnome.org/~walters/docs/build-api.txt

    configure: Drop AM_MAINTAINER_MODE

    config: Add missing AC_CONFIG_SRCDIR
    Regroup AC statements under the Autoconf initialization section.
    Regroup AM statements under the Automake initialization section.

    Remove break statements immediately after return statements
    Silences clang -Wunreachable-code warnings

    Fix const char * warnings

    Add -version option to print program version
    Adds both -version and previously undocumented -help to man page

    Print which option was in error along with usage message

    Combine usage message strings