Fix build to Wine a bit.
It would bomb out on:
freetype.c:166: error: 'FT_MulFix' undeclared here (not in a function)
freetype.c:166: warning: type defaults to 'int' in declaration of 'pFT_MulFix'

This is due to a newer version of freetype. Patch by Shunichi Fuji. Still
fails to compile on other errors, but one more down.