Update to 0.9.5beta1 to fix build with latest libkdcraw package.
digiKam 0.9.5-beta1 - Release date: 2008-11-05

NEW FEATURES:

General        : libkdcraw dependency updated to 0.1.5

Image Editor   : All image plugin tool settings provide default buttons to reset values.
Image Editor   : New Raw import tool to handle Raw pictures with customized decoding settings.
Image Editor   : All image plugin dialogs are removed. All tools are embedded in editor window.

BUGFIXES FROM KDE BUGZILLA (alias B.K.O | http://bugs.kde.org):

001 ==> 166867 : Digikam crashes when starting.
002 ==> 167026 : Crash on startup Directory ImageSubIfd0 not valid.
003 ==> 146870 : Don't reduce size of image when rotating.
004 ==> 167528 : Remove hotlinking URL from tips.
005 ==> 167343 : Albums view corrupted and unusable.
006 ==> 146033 : When switching with Page* image jumps.
007 ==> 127242 : Flashing 'histogram calculation in progress' is a bit annoying.
008 ==> 150457 : More RAW controls in color management pop-up please.
009 ==> 155074 : Edit Image should allow chance to adjust RAW conversion parameters.
010 ==> 155076 : RAW Conversion UI Needs to be more generic.
011 ==> 142975 : Better support for RAW photo handling.
012 ==> 147136 : When selecting pictures from folder showfoto got closed.
013 ==> 168780 : Loose the raw import.
014 ==> 160564 : No refresh of the number of pictures assigned to a tag after removing the tag from some pictures.
015 ==> 158144 : Showfoto crashes in settings window.
016 ==> 162845 : 'Ctrl+F6' Conflict with KDE global shortcut.
017 ==> 159523 : Digikam crashes while downloading images from Olympus MJU 810/Stylus 810 camera no xD card.
018 ==> 161369 : Quick filter indicator lamp is not working properly in recursive image folder view mode.
019 ==> 147314 : Renaming like crazy with F2 slows down my system.
020 ==> 164622 : Crash using timeline when switching from month to week to month view.
021 ==> 141951 : Blank empty context right-click menus.
022 ==> 116886 : Proposal for adding a new destripe/denoise technique.
023 ==> 163602 : Race condition during image download from Camera/ USB device: image corruption and/or loss.
024 ==> 165857 : Unreliable import when photo root is on network share.
025 ==> 147435 : Resize slider in sharpness dialog doesn't work correct.
026 ==> 168844 : Make the selection rectangle draggable over the image (not only resizable).
027 ==> 147151 : Compile error: multiple definition of `jpeg_suppress_tables'.
028 ==> 170758 : High load when tagging
029 ==> 168003 : Drag&dropping a photo to a folder in Dolphin begins copying the whole system:/media.
030 ==> 142457 : Temp files not cleaned up after crashes.

0.9.4:

NEW FEATURES (since 0.9.3):

General : external libsqlite3 depency removed. sqlite3 source code is now included in digiKam core. Note than for packaging, an external libsqlite3 dependency can be used instead internal version (see B.K.O #160966).
General : Updated internal CImg library to last stable 1.2.9 (released at 2008/06/26).
General : English words review in whole GUI by Oliver Dörr.
General : New search text filter for all metadata sidebar tabs.
General : New dialog to list all RAW camera supported. A search camera model tool is available to easily find a camera from list.
General : Creation of tags simplified everywhere. Multiple tags hierarchy can be created at the same time. Tags creation dialog re-designed.
General : Color theme scheme are pervasively applied in graphical interfaces, giving digiKam a real pro-look when dark schemes are selected.
General : Color theme scheme can be changed from either Editor or LightTable.
General : Add capability to display items count in all Album, Date, Tags, and Tags Filter folder views. The number of items contained in virtual or physical albums can be displayed next to its name. If a tree branch is collapsed, parent views sum-up the number of items from all undisplayed children views. Items count is performed in background by digiKam KIO-Slaves. A new option from Setup/Album dialog page can toggle on/off this feature.

ImageEditor : Raw files can be decoded in 16 bits color depth without to use Color Management. An auto-gamma and auto-white balance is processed using the same method than dcraw with 8 bits color depth RAW image decoding. This usefull to to have a speed-up RAW workflow with suitable images.
ImageEditor : New "save as" image file dialog with photo thumbnail / information.

Showfoto : Added support of color theme schemes.
Showfoto : Added 2 options to setup images ordering with "File/Open Folder" action.
Showfoto : New open image file dialog with photo thumbnail / information.

AlbumGUI : Add a new tool to perform Date search around whole albums collection: Time-Line. Timeline is a new left sidebar tab. It's a great tool complementary to the calendar. Try it out!
AlbumGUI : In Calendar View, selecting Year album shows all images of the full year.
AlbumGUI : New status-bar indicator to report album icon view filtering status.
AlbumGUI : Auto-completion in all search text filter.

BUG FIXES:

001 ==> 146393 : No gamma adjustment when opening RAW file.
002 ==> 158377 : digiKam duplicates downloaded images while overwriting existing ones.
003 ==> 151122 : Opening Albums Has Become Very Slow.
004 ==> 145252 : Umask settings used for album directory, not for image files.
005 ==> 144253 : Failed to update old Database to new Database format.
006 ==> 159467 : Misleading error message with path change in digikamrc file.
007 ==> 157237 : Connect the data when using the left tabs.
008 ==> 157309 : digiKam mouse scroll direction on lighttable.
009 ==> 158398 : Olympus raw images shown with wrong orientation.
010 ==> 152257 : Crash on saving images after editing.
011 ==> 153730 : Too many file format options when saving raw image from editor in digiKam.
012 ==> 151157 : Right and left keys goes to first picture and last picture without shortcuts.
013 ==> 151451 : Application crashed using edit.
014 ==> 139657 : Blueish tint in low saturation images converted to CMYK.
015 ==> 147600 : Showfoto Open folder - files shown in reverse order.
016 ==> 149851 : Showfoto asks if you want to save changes when deleting photo, if changes have been made.
017 ==> 138378 : Showfoto opens file browser window to last the folder used upon startup.
018 ==> 148964 : images are blur only inside showFoto.
019 ==> 146938 : Themes Don't Apply To All Panels.
020 ==> 135378 : Single-click on picture open it in editor.
021 ==> 142469 : Splash screen to be the very first thing.
022 ==> 147619 : Crash when viewing video.
023 ==> 136583 : Album icon does not show preview-image after selecting given image as preview.
024 ==> 129357 : Thumbnails not rotated for (D200)-NEF.
025 ==> 132047 : Faster display of images and/or prefetch wished for.
026 ==> 150259 : media-gfx/digikam-0.9.2 error/typo in showfoto.desktop.
027 ==> 150674 : Turn of live update of preview when moving points in curves dialog or in histogram.
028 ==> 141703 : Show file creation date in tooltip.
029 ==> 128377 : Adjust levels: histograms don't match, bad "auto level" function.
030 ==> 141755 : Sidebar: Hide unused tabs, Add tooltips.
031 ==> 146068 : Mixer does not work for green and blue selected as main channel and monochrome mode.
032 ==> 135931 : Reorganize Batch Processing tools from 'Image' and 'Tools' menus.
033 ==> 159664 : Background color of live/quick filter not updated on folder/date change.
034 ==> 096388 : Show number of images in the album.
035 ==> 155271 : Configure suggests wrong parameter for libjasper.
036 ==> 155105 : Broken png image present in albums folder causes digiKam to crash when starting.
037 ==> 146760 : Providing a Timeline-View for quickly narrowing down the date of photos.
038 ==> 146635 : Ratio crop doesn't remember orientation.
039 ==> 144337 : There should be no "empty folders".
040 ==> 128293 : Aspect ratio crop does not respect aspect ratio.
041 ==> 157149 : digiKam crash at startup.
042 ==> 141037 : Search using Tag Name does not work.
043 ==> 158174 : Precise aspect ratio crop feature.
044 ==> 142055 : Which whitebalance is used.
045 ==> 158558 : Delete Function in Tag Filters panel needs to make sure that the tag is unselected when the tag is deleted.
046 ==> 120309 : Change screen backgroundcolor of image tools.
047 ==> 153775 : Download from camera: Renaming because of already existing file does not work.
048 ==> 154346 : Can't rename in digiKam.
049 ==> 154625 : Image-files are not renamed before they are saved to disk.
050 ==> 154746 : Album selection window's size is wrong.
051 ==> 159806 : Cannot display Nikon d3 raw files.
052 ==> 148935 : digiKam hot pixel plugin can not read canon RAW files.
053 ==> 158776 : Confirm tag delete if tag assigned to photos.
054 ==> 148520 : Change of rating causes high CPU load.
055 ==> 140227 : Remove or modify D&D tags menu from icon view area.
056 ==> 154421 : Live search doesn't search filenames.
057 ==> 118209 : digiKam hotplug script kde user detection problem.
058 ==> 138766 : JPEG Rotations: Give a warning when doing Lossy rotations (and offer to do lossless when applicable).
059 ==> 156007 : Canon Raw+Jpg Locks up download image window during thumbnail retrieval.
060 ==> 114465 : Simpler entry of tags.
061 ==> 159236 : Corrupted file when downloading from CF card via digiKam.
062 ==> 121309 : Camera list sorted by brand.
063 ==> 137836 : Usability: Configure camera gui add and auto-detect camera.
064 ==> 160323 : Changing the album name from sth to #sth and then to zsth causes the album to be deleted along with the files.
065 ==> 145083 : Space and Shift-Space isn't used for navigation between images.
066 ==> 158696 : digiKam image viewer crashes when "Save As" is clicked.
067 ==> 156564 : Light table crashes when choosing channel.
068 ==> 147466 : digiKam crashes on termination if an audio file played.
069 ==> 146973 : Crashes when clicking on preview image.
070 ==> 148976 : digiKam Deleted 2.3 g of Pictures.
071 ==> 145252 : Umask settings used for album directory, not for image files.
072 ==> 125775 : digiKam way to save and delete "Searches".
073 ==> 150908 : Canon g3 not recognized works version 0.9.1.
074 ==> 152092 : Showfoto crashes ( signal 11 ) on exit.
075 ==> 160840 : Wrong filtering on Album-Subtree-View.
076 ==> 160846 : Blurred preview of pics.
077 ==> 157314 : Zoom-slider has no steps.
078 ==> 161047 : Shift and wheel mouse doesn't work.
079 ==> 161087 : Conflicting directions of mouse scroll when zooming.
080 ==> 161084 : Not properly updates status bar info.
081 ==> 162132 : Crash while saving tiff (possibly caused by present alpha channel).
082 ==> 155046 : light-table usability, possible improvements.
083 ==> 161085 : Zoom steps in image editor.
084 ==> 162247 : The photos thumbnails list would be better if in the end of an album/date/tag start the next.
085 ==> 160523 : Crash when saving picture as new name after resizing.
086 ==> 162428 : debug info needed ?
087 ==> 147597 : Typos in the digiKam KDE3 PO file.
088 ==> 162496 : When Digikam saves file as JPEG - JPG options are not always presented.
089 ==> 160740 : Handbook says that libgphoto2 is required but does not say whether it should be compiled with exif support.
090 ==> 148400 : Problem loading 16bit Grayscale TIFF image.
091 ==> 160925 : digiKam crash, I don't know why, but I have the bugreport.
092 ==> 162691 : 0.9.4 beta5 compile error imagehistogram.cpp.
093 ==> 160966 : Some searches don't work properly with the new sqlite3-3.5.8.
094 ==> 162245 : Assigned tag list not updated correctly when "show assigned tags" filter is active.
095 ==> 158866 : Advanced Search on Tags a mess.
096 ==> 162814 : digiKam crashes when using light table (page down).
097 ==> 163151 : Red eye correction doesn't work fine.
098 ==> 163227 : Searching for tag names in simple and advanced search doesn't work.
099 ==> 163474 : Config UI using external media.
100 ==> 156420 : Canon EOS 400D, no thumbnails displayed then digikam segfaults.
101 ==> 163118 : digikam-0.9.4_beta5 compilation hangs with gcc 4.3.
102 ==> 164301 : Filter Albums sub-tree names too, when using quickfilter on icon view.
103 ==> 164482 : Place filename of image in klipper/paste buffer from thumbnail right mouse button context menu.
104 ==> 164536 : Add adjust mid range color levels.
105 ==> 164615 : Image detail info about geometry (X-pixel / Y-pixel) missed.
106 ==> 149654 : Fullscreen icon changes image's zoom to 100% (should fit to screen).
107 ==> 162688 : Digikam RC5, can't see scroll bar sliders in dark theme.
108 ==> 161212 : Switch to full screen resets X11.
109 ==> 164432 : Compilation fails with gcc 3.
110 ==> 164392 : Can't compile digikam with missing libkdcraw.
111 ==> 160617 : Same image gets opened to both sides of view when draggin image to right side.
112 ==> 165823 : Digikam crashes if last picture is removed from lighttable.
113 ==> 165921 : Translation bug: Missing german translation.
114 ==> 130906 : Allow user to click text of tags to tag an image (not checkbox only).
115 ==> 126871 : Click on parent folder in tree should generate a reaction.
116 ==> 162812 : Sharpen slider enhancement refresh previews continuously.
117 ==> 166274 : Rename files on download from camera.
118 ==> 166472 : Thumbnail bar gone in image editor when switching back from fullscreen.
119 ==> 166540 : Showfoto always prints filename.